default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: utd_api_dev
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :password) %>

test:
  <<: *default
  database: utd_api_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>