default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: utech_api_dev
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :password) %>
  schema_search_path: utech,public

test:
  <<: *default
  database: utech_api_test
  schema_search_path: utech,public

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    schema_search_path: utech,public